name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "17"

      - uses: android-actions/setup-android@v4

      - uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: "8.11.1"

      - name: Build
        run: gradle assembleDebug assembleRelease

      - uses: actions/upload-artifact@v7
        with:
          name: minimal-launcher
          path: app/build/outputs/apk/**/*.apk
